_target_: src.datamodules.rti_datamodule.LpDataModule
#          src.datamodules.rti_datamodule:
batch_size: 64,
ratio: (10, 2)

data_dir: ${data_dir} # data_dir is specified in config.yaml
num_workers: 0
pin_memory: False
